pnbruckner/homeassistant-config

- custom_components/sun.py
- docs/sun.md
Remove next_rising and next_setting from monitored_conditions options and make them mandatory.
>  (BREAKING CHANGE) Update sun.py to version from PR #15961

- README.md
- custom_components.json
- custom_components/device_tracker/composite.py
- custom_components/device_tracker/life360.py
- custom_components/life360.py
- custom_components/sensor/illuminance.py
- custom_components/sun.py
> Add support for Custom Updater

- custom_components.json
- custom_components/device_tracker/composite.py
- docs/composite.md
Bump version to 1.1.0. Closes #25 and closes #30.
> Composite tracker: Add support for network-based trackers

- README.md
- docs/amcrest.md
- docs/composite.md
- docs/custom_updater.md
- docs/illuminance.md
- docs/life360.md
- docs/life360_lib.md
- docs/sun.md
Use relative URLs where possible. Also fix some links to individual component releases.
> Update doc links

- custom_components.json
- custom_components/device_tracker/composite.py
- docs/composite.md
> Composite tracker: Add support for bluetooth trackers and binary_sensors

- custom_components.json
- custom_components/device_tracker/life360.py
- docs/life360.md
> Life360: Limit speed to non-negative values

- custom_components.json
- custom_components/device_tracker/composite.py
- docs/composite.md
> Composite tracker: Slugify name in schema instead of during setup

- custom_components.json
- custom_components/device_tracker/life360.py
- docs/life360.md
- docs/life360_lib.md
> Life360: Comm module moved to PyPI

- python_scripts/light_store.py
Added the effects attribute so i can save and restore my light effects that were in use, but doesn't error when there is no effect attribute.
> Update to allow saving and restoring of effects

- custom_components.json
- custom_components/sun.py
- docs/sun.md
> Sun: Add max_elevation option

- custom_components.json
> Make trackerfile compliant with 0.88 changes

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/camera.py
https://github.com/home-assistant/home-assistant/pull/22040
> Amcrest: Bump to 1.2.6 & update per HA PR 22040

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/camera.py
Bump amcrest package to 1.3.0.
> Amcrest: Latest updates being submitted

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/camera.py
HA release 0.90.0 (PR #21472) broke the amcrest services. Fix to be compatible with 0.90.0+, as well as previous releases.
> Amcrest: Update per changes in 0.90.0

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/camera.py
Update per review comments in HA PR#22418.
> Amcrest: Update per HA PR

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/camera.py
Simplify implementation where possible. Rename methods to be more consistent. Add services (and corresponding attribute) for enabling/disabling motion recording (in preparation for removing switches.) When enabling recording, make sure video stream is also enabled.
> Amcrest: Prepare for upcoming HA PR

- custom_components.json
- custom_components/amcrest/__init__.py
- custom_components/amcrest/manifest.json
- custom_components/composite/__init__.py
- custom_components/composite/device_tracker.py
- custom_components/composite/manifest.json
- custom_components/life360/__init__.py
- custom_components/life360/device_tracker.py
- custom_components/life360/manifest.json
- docs/amcrest.md
- docs/composite.md
- docs/life360.md
Add `__init__.py` files for remaining components. Also add manifest.json for amcrest.
> Add __init__.py files and update manifests

- custom_components.json
- custom_components/composite/__init__.py
- custom_components/composite/device_tracker.py
- custom_components/life360/__init__.py
- custom_components/life360/device_tracker.py
- docs/composite.md
- docs/life360.md
They need to be in the platform module (like `device_tracker.py`), not `__init__.py`.
> REQUIREMENTS & DEPENDENCIES were in the wrong place

- custom_components.json
- custom_components/life360/__init__.py
- custom_components/life360/device_tracker.py
- docs/life360.md
Fix flake8 & pylint errors. Move some error checking into custom config validators.
> Life360: Lint & config validation

- python_scripts/light_store.py
Fix https://github.com/pnbruckner/homeassistant-config/issues/162
BAD:
GOOD:
> Do not store Attributes with value "null"
