custom_components/device_tracker/life360.py, docs/life360.md
Like other device tracker platforms, if specified and reported gps_accuracy is larger, ignore update.
=> Add max_gps_accuracy to life360.py

custom_components.json, custom_components/device_tracker/life360.py
If multiple errors occur consecutively for a given query or member, only log the first two and then no more until the errors stop. Closes #12.
=> Filter errors in life360

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
Protect against _update_info method being run multiple times concurrently if multiple entities update too close together. Bump version to 1.0.1. Fixes #27.
=> Add thread locking to composite tracker

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
Add an entity_id attribute that is dynamically maintained with the list of "input" entities that have contributed to the current state of the composite device. Suggested in [this community forum post](https://community.home-assistant.io/t/composite-device-tracker-platform/67345/39). Closes #35. Fixes #37.
=> Composite tracker: Add entity_id & last_entity_id attributes and fix binary_sensor bug

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Call _update_life360 as soon as initialization is complete, right before setting up periodic calls. Bump version to 1.6.0b1. Resolves #46.
=> Life360: Update when initialization complete

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
Use util.slugify to make sure config name will be valid device_tracker object ID. Bump version to 1.4.0b1. Resolves #48.
=> Composite tracker: Slugify config name

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
Remove initialization delay and then immediately update by using current states of configured entities, if any. Bump version to 1.5.0.
=> Composite tracker: Initialize and update immediately

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
Log, but otherwise ignore, watched entity state errors during initialization. Improve "skipping" message. Bump version to 1.5.1. Resolves #52.
=> Composite tracker: Ignore watched entity state errors during init

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Apparently there is a limit to the length of an event_type string and the two events this platform fires exceed that length. Shorten them by removing the 'device_tracker.' prefixes. Bump version to 1.6.1. This is a breaking change. Fixes #57.
=> Life360: (BREAKING CHANGE) Shorten event_types

custom_components.json, custom_components/device_tracker/life360.py, custom_components/life360.py, docs/life360.md, docs/life360_lib.md
During startup retrieve Life360 Places and create corresponding zones in HA. Don't use Place if its name is any form of 'home'. Then update periodically (every 15 minutes), removing zones for any Place that has been deleted, and adding zones for any Place that has been added. Bump versions to 1.1.0 for library, and 2.0.0 for device_tracker. Resolves #51.
=> Life360: Create HA zones from Life360 Places

custom_components.json, custom_components/device_tracker/composite.py, docs/composite.md
In addition to 'battery' attribute, also accept 'battery_level' attribute, and use for see method's battery parameter which ultimately becomes device_tracker entity's 'battery' attribute. Accept either 'battery_charging' or 'charging' attribute and use as device_tracker entity's 'battery_charging' attribute. Bump to version 1.6.0. Resolves #60.
=> Composite tracker: Accept 'battery_level' and add 'battery_charging'

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Change charging attribute to the more common battery_charging attribute. Instead of a float, make battery attribute an int like it should have been originally. Bump to 2.1.0. Resolves #61.
=> Life360: (BREAKING CHANGE) Change 'charging' to 'battery_charging' and make 'battery' an int

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Since name of Life360 Place that corresponds to home can be anything, including other languages, add a new, optional config item `home_place` that allows user to specify the name (case insensitive) of this Place. Default to `Home`. Fixes #73.
=> Life360: Add optional home_place config item

custom_components/sensor/illuminance.py
Thu Jan 10 2019 10:59:10 GMT-0600 (CST)
Error loading custom_components.sensor.illuminance. Make sure all dependencies are installed
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 92, in get_component
module = importlib.import_module(path)
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File …
=> Illuminance: Fixes bug with 0.85

custom_components.json, custom_components/sensor/illuminance.py, docs/illuminance.md
In the 0.85 release, homeassistant.components.sensor.darksky changed CONF_ATTRIBUTION to ATTRIBUTION. Change to accept old and new module attribute. Fixes #83.
=> Illuminance: Fixes bug caused by HA 0.85 release

custom_components.json, custom_components/device_tracker/composite.py, custom_components/device_tracker/life360.py, docs/composite.md, docs/life360.md
Add new config item - times_as_local - to cause datetime attributes - such as last_seen & at_loc_since - to be in the local timezone as opposed to UTC. Default to False. Also for life360, move the import of the life360 PyPI module into a try block in case it didn't get installed to handle that scenario better. Resolves #69.
=> Life360 & Composite Trackers: Add option to show datetimes in UTC, local timezone or timezone where device is located

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Communication errors can often happen during normal use. As long as there aren't too many in a row, things seem to work ok. Filter comm errors better by adding two thresholds: warning and error. If the number of times a particular error happens in a row is greater than the error threshold, then log it as an error. If not, but it's greater than the warning threshold, then log it as a warning. Default both thresholds to zero so without a config change it works the way it used to work. Also make "Authenticating" log message INFO instead of DEBUG. Bump to 2.5.0.
=> Life360: Add warning and error thresholds for comm errors

docs/light_store.md, python_scripts.json, python_scripts/light_store.py
Add new overwrite parameter, which only applies to saving and defaults to True. When saving, if overwrite is False, and entities have already been saved, don't overwrite (i.e., skip saving.) Resolves #91.
=> light_store: Add overwrite option

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Add a new choice for the add_zones config variable, specifically include_home_place. If selected, zone.home will be updated to coincide with the Life360 Place whose name matches home_place (case insensitive.) Update to life360 package 2.1.0 (that handles HTTP error 403.) Bump version to 2.6.0b1.
=> Life360: Add include_home_zone choice for add_zones

custom_components.json, custom_components/device_tracker/life360.py, docs/life360.md
Bump life360 package to 2.2.0 which provides unique exception for login errors. Fail setup only on login errors. Log any other errors during setup as warnings and continue. Bump to 2.7.0. Resolves #65.
=> Life360: Fail setup only on login errors

custom_components.json, custom_components_old.json, docs/composite.md, docs/custom_updater.md, docs/illuminance.md, docs/life360.md
Starting with 0.86 custom platforms must be in custom_components/<platform_name>/<domain_name>.py instead of custom_components/<domain_name>/<platform_name>.py. Resolves #100.
=> Adapt to new custom_components folder layout

custom_components.json, custom_components/device_tracker/life360.py, custom_components_old.json, docs/life360.md
Delay overdue update events at startup to give automations time to get ready. Bump to 2.8.0. Resolves #98.
=> Life360: Delay overdue update events at startup

custom_components.json, custom_components/sun/automation.py, docs/sun.md
Merge Custom Updater "elements" "sun" and "sun.automation" into just "sun" by using new resources field in custom_components.json.
=> Merge sun and sun.automation for custom_updater

custom_components.json
Fix for custom_updater. The "name" (main key) of the platform should be in the domain.name format.
https://github.com/custom-components/custom_updater/wiki/components#json-file-examples
=> Update main key to make custom_updater work again

custom_components.json, custom_components/illuminance/sensor.py, custom_components_old.json, docs/illuminance.md
CONF_ATTRIBUTION in homeassistant.components.sensor.yr was renamed to ATTRIBUTION. Bump version to 2.0.2. Resolves #111.
=> Illuminance: Adjust to HA 0.89 release (HA PR #21069)

README.md, custom_components.json, custom_components/amcrest/__init__.py, custom_components/amcrest/binary_sensor.py, custom_components/amcrest/camera.py, docs/amcrest.md
Make import statements work with HA releases prior to 0.86. Add `__version__` to be compatible with custom_updater. Resolves #109.
=> Amcrest: Add backwards compatibility with pre-0.86 and custom_updater

custom_components.json, custom_components/illuminance/__init__.py, custom_components/illuminance/sensor.py, docs/illuminance.md
Apparently custom updater won't process resources unless component has `__init__.py` file.
=> Add __init__.py files

custom_components.json, custom_components/amcrest/__init__.py, custom_components/composite/__init__.py, custom_components/life360/__init__.py, docs/composite.md, docs/life360.md
D'oh! Sure, 0.92 needs manifest.json, but older versions still need REQUIREMENTS and DEPENDENCIES. So keep them both!
=> Still need REQUIREMENTS & DEPENDENCIES for older HA versions

custom_components.json, custom_components/life360/__init__.py, custom_components/life360/device_tracker.py, docs/life360.md
Items imported from device_tracker and zone have changed. Adjust accordingly, while maintaining backwards compatibility. Fixes #147.
=> Life360: Adjust to changes in the upcoming 0.94 release

python_scripts/light_store.py
2023.11 now includes entity attributes whose values are None. Restoring them will cause service call errors.
=> Do not save attributes with value of None
